spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/software_doc_db
    username: root
    password: svts3

  jpa:
    hibernate:
      ddl-auto: create-drop
      